# PromtailがKubernetes APIからPodメタ情報を取得するためのServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.9.4"
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: k8s-observability
    app.kubernetes.io/managed-by: kubectl
